name: e_telly_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.9.3
  flutter_screenutil: ^5.9.3
  geolocator: ^10.1.0 
  camera: ^0.11.3
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  permission_handler: ^11.0.1  
  google_sign_in: ^6.2.1
  mongo_dart: ^0.10.0
  flutter_dotenv: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  http: ^1.2.0 
  geocoding: ^2.1.1
  socket_io_client: ^2.0.1
  provider: ^6.0.5
  connectivity_plus: ^6.0.0
  font_awesome_flutter: ^10.7.0
  flutter_secure_storage: ^10.2.0
  jwt_decoder: ^2.0.1   
  crypto: ^3.0.3  
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^17.2.2
  nearby_connections: ^4.3.0
  device_info_plus: ^10.0.0
  flutter_mapbox_navigation: ^0.2.2
  network_info_plus: ^4.0.0
  uuid: ^4.0.0

 

dependency_overrides:
  flutter_mapbox_navigation:
    path: packages/flutter_mapbox_navigation

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_test: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/videos/Firstaid.mp4
    - assets/videos/Earthquake.mp4
    - assets/videos/Flood.mp4